### ISSUE TITLE
auto-refitting to reduce max final gradient not functioning as expected

### ISSUE THREAD

**Issue by Lewis-Barnett-NOAA** [fate-spatialindicators/non-stationary#2]
The function refit_model_if_needed in code/fit_nonstationary_models_total_cpue_parallel.R is not operating how it should on my machine, as I'm still getting very high max final gradients for some of the AR1 models.  

This all may be a moot point if we're moving to the PC priors approach, but I'm rerunning the AR1 models gain now anyway with additional optimizer steps as a starting point.

**Comment by seananderson** [comment]
Sorry I haven't looked at this yet. It's possible they're just not converging well. If there's a spatial field and an AR1 field, the AR1 can be hard to identify.

Regarding predicting with samples on multiple subregions, I just threw together some code for arrowtooth here: https://github.com/pbs-assess/arrowtooth/blob/e9fe2290afb307cf622aab30a3b778a80a34c98a/presentations/pre-review/twg_01.Rmd#L1416-L1436

where the whole region is predicted on and then it's divided into a bunch of sub-indexes.

Note you'd want `return_sims = FALSE` if you just want quantiles instead of raw samples.

**Comment by seananderson** [comment]
Using the sims can be 8-10 times faster than bias_correct = TRUE. Perhaps even more so for more complex meshes. There's a slight penalty for predicting on more simulation draws, but that scales linearly as it loops over each requested sim replicate.

![image (77)](https://user-images.githubusercontent.com/19349/122275009-11910680-ce98-11eb-9938-5397852c1517.png)

Also, to emphasize, the time spent with the simulation prediction approach is almost entirely on the prediction. get_index_sims() is almost instant—it's just summarizing the existing simulation draws. So, in this case the speed up would be ~8-10 x N_subregions.

**Comment by Lewis-Barnett-NOAA** [comment]
That's great Sean, super promising!  You're probably right that they are just hard to estimate for several species, as I'm still having convergence issues with the original approach.  Let's just try with the PC priors and using the simulation approach for predictions.
